# extra settings to be merged into OpenTelemetry Collector configuration
# do not delete this file
exporters:
  otlp:
    endpoint: "api.honeycomb.io:443"
    headers:
        "x-honeycomb-team": "xnd4kumHKZVZ7Mvv4rD9wB"
      "x-honeycomb-dataset": "webstore-metrics"

service:
  pipelines:
    traces:
      exporters: [otlp, jaeger]
    metrics:
      exporters: [otlp, prometheus]
